#include "cocos2d.h"
USING_NS_CC;

#if(CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AppActivity */

#ifndef _Included_AppActivity
#define _Included_AppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AppActivity
 * Method:    buySuccess
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_buySuccess(JNIEnv *, jobject, jstring, jboolean);


#ifdef __cplusplus
}
#endif
#endif


#endif