#ifndef _VALUE_MAP_H_
#define _VALUE_MAP_H_


#define VALUEMAP_VERSION "VERSION"
#define VALUEMAP_VERSION_NUMBER 1.0

#define VALUEMAP_GAMEMODE_GAME_TYPE "GAMEMODE_GAME_TYPE"
#define VALUEMAP_GAMEMODE_GAME_AMOUNT "GAMEMODE_GAME_AMOUNT"
#define VALUEMAP_GAMEMODE_CLEAR_TOP "GAMEMODE_CLEAR_TOP"
#define VALUEMAP_BOARD "BOARD"



#define VALUEMAP_HAS_TOP_BOUNDARY "HAS_TOP_BOUNDARY"
#define VALUEMAP_HAS_BOTTOM_BOUNDARY "HAS_BOTTOM_BOUNDARY"

#define VALUEMAP_TOP_BOUNDARY "TOP_BOUNDARY"
#define VALUEMAP_BOTTOM_BOUNDARY "BOTTOM_BOUNDARY"

#define VALUEMAP_BUBBLE_WIDTH "BUBBLE_WIDTH"


#define VALUEMAP_BOARD_VECTOR "BOARD_VECTOR"

#define VALUEMAP_DEC2_X "DEC2_X"
#define VALUEMAP_DEC2_Y "DEC2_Y"
#define VALUEMAP_BUBBLE_TYPE "BUBBLE_TYPE"
#define VALUEMAP_PARENT_DEC2_X "PARENT_DEC2_X"
#define VALUEMAP_PARENT_DEC2_Y "PARENT_DEC2_Y"

#define VALUEMAP_BUBBLE_WITCH_FOG_TYPE "BUBBLE_TYPE_2"



//OLD VALUE MAP RELATED CODE
#define PLIST_WIDTH "plist_width"
#define PLIST_HEIGHT "plist_height"
#define PLIST_THREESTAR "plist_threestar"

#define PLIST_DATA "plist_data"
#define PLIST_DATA_WIDTHCOORD "plist_data_widthCoord"
#define PLIST_DATA_HEIGHTCOORD "plist_data_heightCoord"
#define PLIST_DATA_BALLSELECTED "plist_data_ballSelected"

#define PLIST_TIMEMOVE "plist_timeMove"
#define PLIST_TIMEMOVE_BOOL "plist_timeMoveBool"

#define PLIST_CONTAINER "plist_container"
#define PLIST_CONTAINER_WIDTH_COORD "plist_container_widthCoord"
#define PLIST_CONTAINER_HEIGHT_COORD "plist_container_heightcoord"


#endif //_VALUE_MAP_H_